### ISSUE TITLE
Airport missing

### ISSUE THREAD

**Issue by fuelflo** [esperlu/metar#1]
Unfortunately I'm not able to get weather from the new main airport in Dakar DSS/GOBD, while I can get it on aviationweather.gov: https://aviationweather.gov/metar/data?ids=gobd&format=raw&hours=0&taf=on&layout=on&date=0

Would there be a possibility to update the airport list automatically from time to time?

**Comment by esperlu** [comment]
DSS was indeed missing. I have just updated the source and the binaries. About the automatic update of the airport database, it is on my to-do list. Just have to find a reliable source of airport list.

Alternatively, you can always add/update the airport list in the `data/ad_list.g` file and recompile for your environment. Cross compiling with go is a breeze:
https://dave.cheney.net/2015/08/22/cross-compilation-with-go-1-5
https://golang.org/doc/install/source#environment

Thanks for reporting the missing airport.

Cheers.

Jean-Luc

**Comment by fuelflo** [comment]
Thx. Mhm...the problem with this one is, that it is missing the IATA codes for non US Airports https://aviationweather.gov/docs/metar/stations.txt

**Comment by esperlu** [comment]
... and this one is not fully correct.
http://ourairports.com/data/airports.csv

I am thinking of blending the two lists. I will call awk to the rescue!

**Comment by fuelflo** [comment]
Jeah, it's difficult to find a reliable up to date list. At the IATA site you can only query a single airport at a time and at the ICAO site maximum ten.

But I foud this one: https://github.com/datasets/airport-codes
maybe it's of any help.

Cheers
Florian

**Comment by esperlu** [comment]
Hi Florian,

Just in case you are still interested...

I finally have time now to address the update issue (happy retired pilot here!). As my code in metar.go hardcodes all METAR stations (mainly airports) for speed reason, It is not practicable to update the stations on the fly.

The best solution I could come up with is to merge two airport lists and inject the updated lists in the `ad_list.go` source file. Once done with that you will have to recompile `metar.go` with the updated list. The master list is the NOAA list of METAR stations, the slave list is the `ourairport.com` list 

Check this util and report any issue.
https://github.com/esperlu/metar/tree/master/util

Cheers.

Jean-Luc

**Comment by fuelflo** [comment]
Hey Jean-Luc,

honestly, great timing to retire from aviation ;-)

I think it's a good solution to make the program future proof for new airports, without updating the list every time while trying to get some weather. For the two troubles I had while compiling I already created a pull request. The rest works flawlessly.

Viele Grüße
Flo

**Comment by esperlu** [comment]
> 
> honestly, great timing to retire from aviation ;-)
> 

It is indeed. I miss it a bit though! Aviation will recover eventually.
