### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by nremenda** [esperlu/metar#4]
Liking this program so far.  I'm usually using it on a high latency (satellite) internet connection when I'm at work.  This seems to cause the "No Response could be rec...." error.  Is there there a way to increase the wait time for a server response?

**Comment by esperlu** [comment]
If you are ready to compile from [source](https://github.com/esperlu/metar/blob/master/metar.go) which is BTW very easy with Go, you can change the second argument of the function `Wget()` that is called at line 154 and 159. It is set at 2 sec. but you can increase it to whatever value you want. If you want me to build a new binary for you, just let me know for what platform.

Cheers.

Jean-Luc

**Comment by nremenda** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Perfect, I'll give it a shot.Thanks,Neil                                                                                                                                                                                                                                                                                                                        From: notifications@github.comSent: May 11, 2020 00:32To: metar@noreply.github.comReply to: reply@reply.github.comCc: nremenda@gmail.com; author@noreply.github.comSubject: Re: [esperlu/metar] Timeouts (#4)  
If you are ready to compile from source which is BTW very easy wit Go, you can change the second argument of the function Wget() that is called at line 155 and 160. It is set at 2 sec. but you can increase it to whatever value you want. If you want me to build a new binary for you, just let me know for what platform.
Cheers.
Jean-Luc

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by esperlu** [comment]
@nremenda 

Just pushed a refactored version including an option `-t` for timeout so that you can change the default timeout on the fly.

`$ metar -t 5 jfk ebbr thf`

Cheers.

Jean-Luc

**Comment by nremenda** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Cool, thanks.                                                                                                                                                                                                                                                                                                                        From: notifications@github.comSent: June 7, 2020 00:51To: metar@noreply.github.comReply to: reply@reply.github.comCc: nremenda@gmail.com; mention@noreply.github.comSubject: Re: [esperlu/metar] Timeouts (#4)  
@nremenda
Just pushed a refactored version including an option -t for timeout so that you can change the default timeout on the fly.
$ metar -t 5 jfk ebbr thf
Cheers.
Jean-Luc

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
