### ISSUE TITLE
Data (source?) issue

### ISSUE THREAD

**Issue by genys123** [esperlu/metar#7]
It appears that some data is incorrect:

1.
$ metar -la Lv

  Latvia (EU)
  EVLA LPX LV Liepāja International Airport (Liepāja)
  EVRA RIX LV Riga International Airport (Riga)
  EVVA VNT LV Ventspils International Airport (Ventspils)
  UMRR     LV RIGA
  UMRW     LV VENTSPILS (HARBO

UMRR UMRW if exist, certainly are not in Latvia EVxx

2
$ metar -f plq

EYPA (PLQ) Palanga International Airport (Palanga), Lithuania LT (EU)
No TAF received for this station

2.4.1 | Download: 0.263 sec. | Process: 0.011 sec. | Total: 0.274 sec.

Palanga certainly has TAF. 

Might some outdated sources are used?

V.

**Comment by esperlu** [comment]
The data source might indeed be outdated. I'll check.

Thanks for reporting

**Comment by esperlu** [comment]
`UMRR UMRW if exist, certainly are not in Latvia EVxx`
Correct, UMxx is either Belarus or the Kaliningrad exclave. I will notify the airport data source (`ourairports.com`)

As for the TAF for EYPA,   airports occasionally fail to upload their TAF's on time to the NOAA aviationweather.gov web site. This can trigger a temporary `No TAF received for this station`

No problem today.

go run metar.go PLQ

```
EYPA (PLQ) Palanga International Airport (Palanga), Lithuania LT (EU)
EYPA 201820Z 22005KT 190V270 9999 FEW016 02/M01 Q0998 [-1 2 81%]
EYPA 201750Z 24006KT 200V300 9999 FEW018 03/M00 Q0998 [0 3 81%]
EYPA 201720Z 24006KT 210V340 9999 SCT016 03/00 Q0998 [0 3 81%]
EYPA 201650Z VRB07KT 9999 SCT016 BKN033 03/00 Q0999 [-0 3 81%]
TAF 201700Z 2018/2118 16012KT 9000 BKN015 TEMPO 2018/2021 22010KT TEMPO 2021/2107 3000 RA BR BKN005 BECMG 2107/2109 22015G35KT TEMPO 2111/2118 23025G45KT 3000 SHRASN BKN005 BKN012CB
```

**Comment by esperlu** [comment]
`UMRR UMRW if exist, certainly are not in Latvia EVxx`
Correct, UMxx is either Belarus or the Kaliningrad exclave. I will notify the airport data source (`ourairports.com`)

As for the TAF for EYPA,   airports occasionally fail to upload their TAF's on time to the NOAA aviationweather.gov web site. This can trigger a temporary `No TAF received for this station`

No problem today.

go run metar.go PLQ

```
EYPA (PLQ) Palanga International Airport (Palanga), Lithuania LT (EU)
EYPA 201820Z 22005KT 190V270 9999 FEW016 02/M01 Q0998 [-1 2 81%]
EYPA 201750Z 24006KT 200V300 9999 FEW018 03/M00 Q0998 [0 3 81%]
EYPA 201720Z 24006KT 210V340 9999 SCT016 03/00 Q0998 [0 3 81%]
EYPA 201650Z VRB07KT 9999 SCT016 BKN033 03/00 Q0999 [-0 3 81%]
TAF 201700Z 2018/2118 16012KT 9000 BKN015 TEMPO 2018/2021 22010KT TEMPO 2021/2107 3000 RA BR BKN005 BECMG 2107/2109 22015G35KT TEMPO 2111/2118 23025G45KT 3000 SHRASN BKN005 BKN012CB
```

**Comment by esperlu** [comment]
I have modified the `util/updateStations.go` file has the NOAA file contains errors. The corrected airport data's does not show UMRR in LV anymore.

```
$ go run metar.go -la lv
  Latvia (EU)
  EVGA     LV Lielvarde Air Base (Lielvarde)
  EVLA LPX LV Liepāja International Airport (Liepāja)
  EVRA RIX LV Riga International Airport (Riga)
  EVVA VNT LV Ventspils International Airport (Ventspils)

  Processed in 8.339 ms.

```

I will compile the binaries shortly.

**Comment by genys123** [comment]
Strange to see this issue again...

:~$ date
2022-12- 11 19:53:56 EET

:~$ metar -la lv


  Latvia (EU)
  EVLA LPX LV Liepāja International Airport (Liepāja)
  EVRA RIX LV Riga International Airport (Riga)
  EVVA VNT LV Ventspils International Airport (Ventspils)
  UMRR     LV RIGA
  UMRW     LV VENTSPILS (HARBO

  Processed in 22.165 ms.
