### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by BerryBerryTart** [esperlu/metar#9]
Getting page not found when making queries

**Comment by esperlu** [comment]
Yes, indeed. Probably aviationweather.gov changed something. Will investigate and possibly correct the code.

**Comment by esperlu** [comment]
aviationweather.gov changed its API. Fixed in the latest release. Thanks for reporting.

**Comment by fuelflo** [comment]
Thx for the quick fix J.L.!

Unfortunately it also seems to be impossible to update the Stations, due to the changes made on aviationweather.gov, as they don't seem to provide a station list at that location anymore.

```
go run updateStations.go 
2023/10/18 21:05:04 

 Error: Get https://www.aviationweather.gov/docs/metar/stations.txt
 HTTP error: Not Found

exit status 1
```

**Comment by esperlu** [comment]
This is another annoyance. The purpose of downloading the deprecated  AviationWeather.gov METAR station list was to only compute data for the stations that have a METAR reporting service. The new API only provides a gzipped file that contains all the stations that have a current METAR, but it does not include stations that have a METAR reporting service that is closed at the time of creation of the file. I am working at it and I am open to any suggestions.

**Comment by ni720** [comment]
Hi J.L.,

how about taking the complete list of all airports and if the user requests, send a query to avweather.gov and if that station has no or at the time no METAR, simply tell the user.

A "complete" list can be found here: https://ourairports.com/data/

The list can be filtered to sort out closed stations and heliports or seaplane bases for example.

Thanks for keeping this tool working!
BR, Martin

**Comment by esperlu** [comment]
Hi Martin,

That's what the code actually does. It takes the ourairports.com airport list and corrects it against the aiviationweather.gov list when it encounters funky data (e.g., airport coordinates).

Quick fix available now in the `utils` directory. Thanks for your input.

Cheers

Jean-Luc

**Comment by esperlu** [comment]
I just received a response to my request to NOAA (aviationweather.gov) informing me that the NOAA developers are working on providing a similar file to replace stations.txt.

For the time I close this issue.

Cheers,

Jean-Luc
